version: '3.8'

services:
  resume-screening:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2:1b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/app/uploads
      - ./JD.txt:/app/JD.txt
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge